"""Motley Crews environment: observation encoding and turn action types (engine in 4.3)."""

from motley_crews_env.constants import (
    BOARD_SIZE,
    CLASS_IDS,
    DEFAULT_POINTS_TO_WIN,
    FIGURES_PER_SIDE,
    MAX_CURSE_X,
    NUM_CLASSES,
    NUM_SPECIAL_IDS,
    SPECIAL_IDS,
)
from motley_crews_env.encoding import (
    SPEC,
    ObservationTensorSpec,
    encode_observation,
    global_vector_layout,
    structured_observation_to_global_vector,
    structured_observation_to_tensor,
    tensor_shapes,
)
from motley_crews_env.serialization import turn_action_from_tuple, turn_action_to_tuple
from motley_crews_env.types import (
    ActionBasicAttack,
    ActionIntent,
    ActionSpecial,
    ClassId,
    MoveIntent,
    Phase,
    SpecialId,
    StructuredObservation,
    TeamId,
    TerrainCode,
    TurnAction,
)

__all__ = [
    "BOARD_SIZE",
    "CLASS_IDS",
    "DEFAULT_POINTS_TO_WIN",
    "FIGURES_PER_SIDE",
    "MAX_CURSE_X",
    "NUM_CLASSES",
    "NUM_SPECIAL_IDS",
    "SPECIAL_IDS",
    "SPEC",
    "ObservationTensorSpec",
    "encode_observation",
    "global_vector_layout",
    "structured_observation_to_global_vector",
    "structured_observation_to_tensor",
    "tensor_shapes",
    "turn_action_from_tuple",
    "turn_action_to_tuple",
    "ActionBasicAttack",
    "ActionIntent",
    "ActionSpecial",
    "ClassId",
    "MoveIntent",
    "Phase",
    "SpecialId",
    "StructuredObservation",
    "TeamId",
    "TerrainCode",
    "TurnAction",
]
