"""Motley Crews environment: rules engine, observation encoding, and turn actions."""

from motley_crews_env.constants import (
    BOARD_SIZE,
    CLASS_IDS,
    DEFAULT_POINTS_TO_WIN,
    FIGURES_PER_SIDE,
    MAX_CURSE_X,
    NUM_CLASSES,
    NUM_SPECIAL_IDS,
    SPECIAL_IDS,
)
from motley_crews_env.encoding import (
    SPEC,
    ObservationTensorSpec,
    encode_observation,
    global_vector_layout,
    structured_observation_to_global_vector,
    structured_observation_to_tensor,
    tensor_shapes,
)
from motley_crews_env.engine import (
    begin_setup,
    complete_setup_random,
    initial_play_state,
    initial_state,
    legal_actions,
    legal_setup_actions,
    scenario_from_placements,
    setup_step,
    step,
    to_structured_observation,
)
from motley_crews_env.serialization import turn_action_from_tuple, turn_action_to_tuple
from motley_crews_env.state import GameState, IllegalActionError, StepResult
from motley_crews_env.types import (
    ActionBasicAttack,
    ActionIntent,
    ActionSpecial,
    ClassId,
    MatchPhase,
    MoveIntent,
    Phase,
    SetupPlacement,
    SpecialId,
    StructuredObservation,
    TeamId,
    TerrainCode,
    TurnAction,
)

__all__ = [
    "BOARD_SIZE",
    "CLASS_IDS",
    "DEFAULT_POINTS_TO_WIN",
    "FIGURES_PER_SIDE",
    "MAX_CURSE_X",
    "NUM_CLASSES",
    "NUM_SPECIAL_IDS",
    "SPECIAL_IDS",
    "SPEC",
    "ObservationTensorSpec",
    "encode_observation",
    "global_vector_layout",
    "structured_observation_to_global_vector",
    "structured_observation_to_tensor",
    "tensor_shapes",
    "turn_action_from_tuple",
    "turn_action_to_tuple",
    "ActionBasicAttack",
    "ActionIntent",
    "ActionSpecial",
    "ClassId",
    "MatchPhase",
    "MoveIntent",
    "Phase",
    "SetupPlacement",
    "SpecialId",
    "StructuredObservation",
    "TeamId",
    "TerrainCode",
    "TurnAction",
    "GameState",
    "IllegalActionError",
    "StepResult",
    "begin_setup",
    "complete_setup_random",
    "initial_play_state",
    "initial_state",
    "legal_actions",
    "legal_setup_actions",
    "setup_step",
    "step",
    "to_structured_observation",
    "scenario_from_placements",
]
